### PR TITLE
Major feature additions

### PR DESCRIPTION
**Pull request by Aliencreature**
Quick Summary:
Clan XL and XXL Engines
IS XXL and Compact Engines
IS Endo-Composite
IS Light, Heavy Ferro
IS Stealth Armor
Clan Endo + Ferro
Small Cockpit (WIP)

Most of it is just activations of features you already put in (Clan stuff), but I made a few additions.

XXL Engines: Occupy 6 (IS) or 4 (Clan) slots in each side torso and produce +15 heat per turn.
Endo-Composite: Occupies 7 slots, reduces internal structure weight by 25%.
Small Cockpit: Weighs 2 tons instead of 3. Haven't figured out how to add its tabletop injury chance penalty.
Stealth Armor: Occupies 12 slots total (6 chunks of 2). Provides +2 difficulty to hit, but generates +10 heat per turn. Normally it would require ECM, but I haven't implemented any yet because I am not so sure it is within the scope of this mod.
Compact Engines: Occupy only 3 slots, but weigh 50% more than STD engines. Seems very niche and perhaps limited to mechs that can't otherwise use their CT hardpoints.

Also fixed the way you defined new structure/armor types in the settings. I ran into the problem of having too many things in the store and not all of them showing, but in its final form they won't all spawn at the same time anyway.

Other than that, everything works. The balance gets a bit funny with the Clan tech because the AI can't use it, but the costs are prohibitive for most of it.

### CODE REVIEW

**Comment by CptMoore** [comment]
hey there thanks for taking the time for this, however there are a few issues:
* the more items the slower the game is. I was thinking of reducing the amount of XL engines further (like maybe only 2 engine ratings) and moving LFE out of the standard install. now while I appreciate your effort, I would maybe move most engines to a "disabled/" folder and also create new shop files that are moved there too. if HBS fixes the mechlab performance issues, we can introduce more engines again. Same goes for the additional armor and structure. Only stuff that has own code should be enabled by default
* make sure your UINames don't break newlines and the model text does not ellipses "..." (the light engine stuff had issues, I see you changes some stuff, but I made a rewrite of all)
* all those generate.sh files now have lots of code clones, I would prefer a single generate file again, whats the issue here?
* the whole MechEngineModSettings.cs file is claimed to be new, newline issues? github issue?
* I am right now moving es and ff to upgrades (internals/) and as they didn't fit the heatsink category anymore. also changed the UIName and Model. will commit that soon.
* Small cockpits also use one less slot by removing the life systems. I would enlarge all cockpits to 2 slots, give the head one more slot to work with and then the small cockpit is only one slot high.

> Also fixed the way you defined new structure/armor types in the settings

did I miss that in the PR? looks the same as before?

> Stealth Armor: Occupies 12 slots total (6 chunks of 2). Provides +2 difficulty to hit, but generates +10 heat per turn. Normally it would require ECM, but I haven't implemented any yet because I am not so sure it is within the scope of this mod.

I think the whole armor and structure part of out of scope of the mod. the only reason I didn't move it out to another mod is that the tonnage calculations summary (in the mechlab top left) has some code that can't be easily shared, I would need to create a third mod that allows to properly overwrite the summary stat.

Of course I could do that myself but just not enough time. (create the tonnage summary mod, move out structure and armor mods to own mod)

**Comment by Aliencreature** [comment]
>the more items the slower the game is. I was thinking of reducing the amount of XL engines further (like maybe only 2 engine ratings) and moving LFE out of the standard install. now while I appreciate your effort, I would maybe move most engines to a "disabled/" folder and also create new shop files that are moved there too. if HBS fixes the mechlab performance issues, we can introduce more engines again. Same goes for the additional armor and structure. Only stuff that has own code should be enabled by default

I wonder if leaving all the options enabled in the MechEngineModSettings.cs (which for some reason it's showing as entirely new? Probably a github issue, I just changed a few lines) and not including more than the basics in the base mod would work. So, for example, the line that defines the XXL type would be there, but no XXL engines are included by default.

Could other mods register the engine components? In that case, I could make a second mod that adds the advanced tech without messing with your intended scope. I will test it tonight.

>make sure your UINames don't break newlines and the model text does not ellipses "..." (the light engine stuff had issues, I see you changes some stuff, but I made a rewrite of all)

Yup, saw that and am still trying to figure out the naming conventions. The problematic engines I saw were Clan XXL (could become cXXL), Compact Engine (could become simply Compact XXX) and most of the Left/Right, maybe turning it into L/R will fix it.

> all those generate.sh files now have lots of code clones, I would prefer a single generate file again, whats the issue here?

Didn't want to include everything in case the additional items (Clan, XXL, Compact) weren't included in the main mod. It'll be trivial to make a single generate.sh again, I can get to it tonight.

>I am right now moving es and ff to upgrades (internals/) and as they didn't fit the heatsink category anymore. also changed the UIName and Model. will commit that soon.

Gotcha, I'll look at them when you do.

>did I miss that in the PR? looks the same as before?

It worked fine for the ones you had enabled, but as an example, ClanEndo didn't work because it was set like this:

`new StructureType { ComponentDefId = "emod_structureslots_clanendosteel", RequiredCriticalSlotCount = 7, WeightSavingsFactor = 0.5f },
`
instead of:

`new WeightSavingSlotType { ComponentDefId = "emod_structureslots_clanendosteel", RequiredCriticalSlotCount = 7, WeightSavingsFactor = 0.5f },`

**Comment by CptMoore** [comment]
> Could other mods register the engine components? In that case, I could make a second mod that adds the advanced tech without messing with your intended scope. I will test it tonight.

thats a good idea, you could prepare a mod in a subdirectory in this repo with all engines generated and enabled, so people would only need to move it to the parent directory and all engines are there.

I wouldn't suggest doing your own repo for now, since if I refactor stuff I can keep your additions in mind

**Comment by CptMoore** [comment]
I've added you as a collaborator, so you can create branches directly in this repo and merge your own PRs after I reviewed them. try to keep the PRs small so I can quickly approve them.

**Comment by Aliencreature** [comment]
Excellent! I'll get on it then!

**Pull request closed without merging**
