### PR TITLE
Light Fusion Engines

### PR DESCRIPTION
**Pull request by Aliencreature**
Added Light Fusion Engines using the built-in functionality. Seems to be working so far, although more testing might be needed to make sure they work differently from XL engines in combat.

### CODE REVIEW

**Comment by CptMoore** [comment]
Theree are some whitespaces that are off a bit, but i dont mind

**Comment by CptMoore** [comment]
Github is not mobile friendly....

**Comment by Aliencreature** [comment]
Yeah, it was a little sloppy on my end because I was juggling play-testing and adding it to the stores at the same time. Sorry about that!

**Comment by CptMoore** [comment]
If you feel you are finished testing your changes just press the merge button

**Comment by Aliencreature** [comment]
I did, but it's not showing me the merge button for some reason. Weird. I know where it should be, but it's just... not there.

**Comment by CptMoore** [comment]
Ok let me try some settings

**Comment by CptMoore** [comment]
Oh ok, so i would need to add you to the collaborators list. Ill just press the merge button.

**Pull request merged**
